CONCEPT_SEED_DATA = [
    {"canonical_name": "sliding_window", "display_name": "Sliding Window",
     "aliases": ["sliding window", "sliding window technique", "window sliding", "two-pointer window"]},
    {"canonical_name": "two_pointers", "display_name": "Two Pointers",
     "aliases": ["two pointer", "two pointers", "two-pointer technique", "dual pointer"]},
    {"canonical_name": "hash_map", "display_name": "Hash Map / Hashing",
     "aliases": ["hash map", "hashmap", "hash table", "hashing", "dictionary lookup"]},
    {"canonical_name": "binary_search", "display_name": "Binary Search",
     "aliases": ["binary search", "binary search on answer", "bsearch"]},
    {"canonical_name": "dp", "display_name": "Dynamic Programming",
     "aliases": ["dynamic programming", "dp", "memoization", "tabulation"]},
    {"canonical_name": "graph_traversal", "display_name": "Graph Traversal (BFS/DFS)",
     "aliases": ["bfs", "dfs", "breadth first search", "depth first search", "graph traversal"]},
    {"canonical_name": "monotonic_stack", "display_name": "Monotonic Stack",
     "aliases": ["monotonic stack", "monotonic deque", "increasing stack", "decreasing stack"]},
    {"canonical_name": "heap_priority_queue", "display_name": "Heap / Priority Queue",
     "aliases": ["heap", "priority queue", "min heap", "max heap"]},
    {"canonical_name": "greedy", "display_name": "Greedy",
     "aliases": ["greedy", "greedy algorithm", "greedy approach"]},
    {"canonical_name": "backtracking", "display_name": "Backtracking",
     "aliases": ["backtracking", "recursion with pruning", "brute force with pruning"]},
    {"canonical_name": "union_find", "display_name": "Union-Find / DSU",
     "aliases": ["union find", "disjoint set union", "dsu"]},
    {"canonical_name": "prefix_sum", "display_name": "Prefix Sum",
     "aliases": ["prefix sum", "cumulative sum", "running sum"]},
    {"canonical_name": "bit_manipulation", "display_name": "Bit Manipulation",
     "aliases": ["bit manipulation", "bitmask", "bitwise operations"]},
    {"canonical_name": "trie", "display_name": "Trie",
     "aliases": ["trie", "prefix tree"]},
    {"canonical_name": "segment_tree", "display_name": "Segment Tree",
     "aliases": ["segment tree", "fenwick tree", "binary indexed tree"]},
]