"""add uq_platform_external_id constraint

Revision ID: 8db71bf533fb
Revises: 342874ededf7
Create Date: 2026-07-07 12:45:38.565324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db71bf533fb'
down_revision: Union[str, Sequence[str], None] = '342874ededf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_platform_external_id', 'contests', ['platform', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_platform_external_id', 'contests', type_='unique')
    # ### end Alembic commands ###
