"""add weakness tracking tables

Revision ID: fe31f91d2381
Revises: 8db71bf533fb
Create Date: 2026-07-07 13:02:57.442702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe31f91d2381'
down_revision: Union[str, Sequence[str], None] = '8db71bf533fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('weakness_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_tag_id', sa.UUID(), nullable=False),
    sa.Column('gap_count', sa.Integer(), nullable=False),
    sa.Column('last_flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_resurfaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active_weakness', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_tag_id'], ['concept_tags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_tag_id', name='uq_user_concept')
    )
    op.create_table('submission_concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('concept_tag_id', sa.UUID(), nullable=False),
    sa.Column('was_flagged_as_gap', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_tag_id'], ['concept_tags.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['code_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_concepts')
    op.drop_table('weakness_records')
    op.drop_table('concept_tags')
    # ### end Alembic commands ###
